apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret # This is the secret of the docker registry
      containers:
        - name: frontend
          image: /frontend:3e0427c7128538dc8031f55a6c2f42952ffa3917
          env:
            - name: ANGULAR_APP_BACKEND_URL
              value: "https://api.nausicaaglobalgreen.live/api/" # This is the backend URL
          ports:
            - containerPort: 4200
